Пример 1.2.1

Создать массив 5x2. Создать массив 5x2. Вывести все значения массива,
значение элемента с индексом (3,1) и второй столбец. Индексация
начинается с нуля.

In [3]:
import numpy as np


x = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
print(x)
print(x[3][1])
print(x[1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[3 4]


Пример 1.2.2

Выполнить следующее:
1. Создать вектор (одномерный массив) размера 10, заполненный нулями.
2. Создать вектор размера 10, заполненный единицами.
3. Создать вектор размера 10, заполненный заданным числом.
4. Создать вектор со значениями от 10 до 19

In [5]:
import numpy as np


x = np.zeros(10)
y = np.ones(10)
z = np.full(10, 5)
v = np.arange(10, 20)
print(x)
print(y)
print(z)
print(v)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5 5 5 5 5 5 5 5 5 5]
[10 11 12 13 14 15 16 17 18 19]


Пример 1.2.3

Создать массив 10x10 со случайными значениями, найти минимум,
максимум и среднее значение.

In [6]:
import numpy as np


mas = np.random.random((10, 10))
print("Min=", mas.min(), ", Max=", mas.max(), ", Mean=", mas.mean())

Min= 0.0009125202209057104 , Max= 0.9919268906908654 , Mean= 0.4507332407720984


Пример 1.2.4

Задать матрицу размерности 5 на 5 и поменять 2 строки в матрице
местами.

In [12]:
import numpy as np


matrix = np.arange(25).reshape(5, 5)S
matrix[[0, 1]] = matrix[[1, 0]]
print(matrix)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


Пример 1.2.5

Выяснить результат следующих выражений:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

In [13]:
import numpy as np


print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


Пример 1.2.6

Отсортировать массив.

In [15]:
import numpy as np


arr = np.array([5, 4, 3, 2, 1])
print(np.sort(arr))

[1 2 3 4 5]


Задание 1.3.1

Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и
единицами.

In [15]:
import numpy as np


Z = np.zeros((8,8), dtype = int)
Z[1::2, ::2] = 1
Z[::2, 1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Пример 1.3.2

Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания
необходимо использовать функцию arrange.

In [9]:
import numpy as np


Z = np.zeros((5,5), dtype = int)
Z += np.arange(5)
print(Z)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


Пример 1.3.3

Создать массив 3x3x3 со случайными значениями.

In [14]:
import numpy as np


Z = np.random.random((3, 3, 3))
print(Z)

[[[0.55441426 0.55054993 0.83759296]
  [0.92234103 0.45584281 0.78969863]
  [0.47896965 0.45247068 0.3534812 ]]

 [[0.8325172  0.59226957 0.27748351]
  [0.85057566 0.40647626 0.81146403]
  [0.26366868 0.66185335 0.47402028]]

 [[0.54604459 0.42926077 0.31587742]
  [0.06478608 0.64025238 0.78155983]
  [0.49583128 0.85458123 0.16777669]]]


Пример 1.3.4

Создать матрицу с 0 внутри, и 1 на границах.

In [23]:
import numpy as np


Z = np.ones((5,5), dtype=int)
Z[1:-1:,1:-1:] = 0
print(Z)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


Пример 1.3.5

Создайте массив и отсортируйте его по убыванию.

In [31]:
import numpy as np


Z = np.array(range(14))
Z.sort()
Z = Z[::-1]
print(Z)

[13 12 11 10  9  8  7  6  5  4  3  2  1  0]


Пример 1.3.6

Создайте матрицу, выведите ее форму, размер и размерность.

In [39]:
import numpy as np


Z = np.random.random((5,5))
print("Форма матрицы:")
print(Z.shape)
print("Размер матрицы:")
print(Z.size)
print("Размерность матрицы:")
print(Z.ndim)

Форма матрицы:
(5, 5)
Размер матрицы:
25
Размерность матрицы:
2


Пример 2.2.1

Создать Series из списка Python, словаря Python, и массива Numpy
(установить буквенные метки для последнего).

In [4]:
import pandas as pd
import numpy as np


lst = [1, 2, 3, 4, 5]
d = {"a": 1, "b": 2, "c": 3}
ndarr = np.array([1, 2, 3, 4, 5])
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series(d)
s3 = pd.Series(ndarr, ['a', 'b', 'c', 'd', 'e'])
print(s1, s2, s3)

0    1
1    2
2    3
3    4
4    5
dtype: int64 a    1
b    2
c    3
dtype: int64 a    1
b    2
c    3
d    4
e    5
dtype: int32


Пример 2.2.2

Дано два Series. Напечатать их первые элементы и все элементы после
третьего (во втором фрейме)

In [7]:
s1 = pd.Series(ndarr, ['a', 'b', 'c', 'd', 'e'])
s2 = pd.Series([5, 4, 3, 2, 1])
print(s1['a'])
print(s2[0])
print(s2[3:])

1
5
3    2
4    1
dtype: int64


Пример 2.2.3

Создайте новый фрейм данных.

In [8]:
df = pd.DataFrame()
df["Имя"] = ['Джеки Джексон', 'Стивен Стивенсон']
df["Возраст"] = [38, 35]
df["Водитель"] = [True, False]
df

Имя  Возраст  Водитель
0     Джеки Джексон       38      True
1  Стивен Стивенсон       35     False

Пример 2.2.4

Загрузите фрейм данных по ссылке:
https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titan
ic.csv

In [9]:
url = "https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv"
df = pd.read_csv(url)
df.head(5)

Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female   
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92    male   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1  
4         1        0

Пример 2.2.5

Пронализировать характеристики фрейма данных.

In [11]:
print(df.head(2))
print(df.tail(3))
print(df.shape)
print(df.describe())

                           Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1
                  Name PClass   Age   Sex  Survived  SexCode
1310  Zenni, Mr Philip    3rd  22.0  male         0        0
1311  Lievens, Mr Rene    3rd  24.0  male         0        0
1312    Zimmerman, Leo    3rd  29.0  male         0        0
(1313, 6)
              Age     Survived      SexCode
count  756.000000  1313.000000  1313.000000
mean    30.397989     0.342727     0.351866
std     14.259049     0.474802     0.477734
min      0.170000     0.000000     0.000000
25%     21.000000     0.000000     0.000000
50%     28.000000     0.000000     0.000000
75%     39.000000     1.000000     1.000000
max     71.000000     1.000000     1.000000


Пример 2.2.6

Выберите индивидуальные данные или срезы фрейма данных.

In [12]:
df.iloc[1:4]

Name PClass   Age     Sex  \
1                    Allison, Miss Helen Loraine    1st   2.0  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.0    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.0  female   

   Survived  SexCode  
1         0        1  
2         0        0  
3         0        1

Пример 2.2.7

Требуется отобрать строки фрейма данных на основе некоторого
условия. Необходимо сформировать новый фрейм данных из пассажиров
первого класса.

In [13]:
df[df['PClass'] == '1st'].head(2)

Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

Пример 2.3.1

Найдитн евклидово расстояние между двумя Series (точками) a и b, не
используя встроенную формулу.

In [1]:
import pandas as pd


print(sum((pd.Series([1, 2, 3, 4])-pd.Series([5, 6, 7, 8]))**2)**.5)

8.0


Пример 2.3.2

Найдите в Интернете ссылку на любой csv файл и сформируйте из него
фрейм данных (например, коллекцию фреймов данных можно найти
здесь: https://github.com/akmand/datasets).

In [2]:
import pandas as pd


url = "https://raw.githubusercontent.com/akmand/datasets/main/baby_names_2000.csv"
dataframe = pd.read_csv(url)
dataframe.head(5)

year     name gender  count
0  2000    Emily      F  25956
1  2000   Hannah      F  23082
2  2000  Madison      F  19968
3  2000   Ashley      F  17997
4  2000    Sarah      F  17702

Пример 2.3.3

Проделайте с получившемся из предыдущего задания фреймом данных
те же действия, что и в примерах 2.2.5-2.2.7.

In [15]:
import pandas as pd


url = "https://raw.githubusercontent.com/akmand/datasets/main/baby_names_2000.csv"
#2.2.5
dataframe = pd.read_csv(url)
dataframe.head(2)
dataframe.tail(3)
dataframe.shape
dataframe.describe()
#К2.2.6
dataframe.iloc[1:4]
#2.2.7
dataframe[dataframe['name'] == 'Jennifer'].head(2)

year      name gender  count
25     2000  Jennifer      F   9386
20489  2000  Jennifer      M     32

Пример 3.2.1

Прошкалируйте числовой признак в диапазон между двумя значениями.

In [2]:
import numpy as np
from sklearn import preprocessing


feature = np.array([[-500.5], [-100.1], [0], [100.1], [900.9]])
minmax_scale = preprocessing.MinMaxScaler(feature_range = (0, 1))
scaled_feature = minmax_scale.fit_transform(feature)
scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

Пример 3.2.2

Преобразуйте признак, чтобы он имел среднее значение 0 и стандартное
отклонение 1.

In [6]:
x = np.array([[-1000.1], [-200.2], [500.5], [600.6], [9000.9]])
scaler = preprocessing.StandardScaler()
standardized = scaler.fit_transform(x)
print(standardized)
print(round(standardized.mean()))
print(round(standardized.std()))

[[-0.76058269]
 [-0.54177196]
 [-0.35009716]
 [-0.32271504]
 [ 1.97516685]]
0
1


Пример 3.2.3

Дан фрейм данных
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
'B':[103.02,107.26,110.35,114.23,114.68],
'C':['big','small','big','small','small']})
Необходимо масштабировать его числовые столбцы.

In [7]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler


scaler = MinMaxScaler()
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21], 'B':[103.02,107.26,110.35,114.23,114.68], 'C':['big','small','big','small','small']})
dfTest[['A', 'B']] = scaler.fit_transform(dfTest[['A', 'B']])
dfTest

A         B      C
0  0.000000  0.000000    big
1  0.926219  0.363636  small
2  0.935335  0.628645    big
3  1.000000  0.961407  small
4  0.938495  1.000000  small

Пример 3.3.2

Загрузить фрейм данных по ссылке:
https://raw.githubusercontent.com/akmand/datasets/master/iris.csv.
Необходимо выполнить нормализацию первого числового признака
(sepal_length_cm) с использованием минимаксного преобразования, а
второго (sepal_width_cm) с задействованием z-масштабирования.

In [4]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler


url = "https://raw.githubusercontent.com/akmand/datasets/master/iris.csv"
dataframe = pd.read_csv(url)
scalerM = MinMaxScaler()
dataframe[['sepal_length_cm']] = scalerM.fit_transform(dataframe[['sepal_length_cm']])
scalerZ = StandardScaler()
dataframe[['sepal_width_cm']] = scalerZ.fit_transform(dataframe[['sepal_width_cm']])
dataframe

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0           0.222222        1.032057              1.4             0.2   
1           0.166667       -0.124958              1.4             0.2   
2           0.111111        0.337848              1.3             0.2   
3           0.083333        0.106445              1.5             0.2   
4           0.194444        1.263460              1.4             0.2   
..               ...             ...              ...             ...   
145         0.666667       -0.124958              5.2             2.3   
146         0.555556       -1.281972              5.0             1.9   
147         0.611111       -0.124958              5.2             2.0   
148         0.527778        0.800654              5.4             2.3   
149         0.444444       -0.124958              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]